apiVersion: v1
kind: Pod
metadata:
  name: terraform-editor
spec:
  containers:
    - name: busybox
      image: "busybox"
      command: [ "sleep", "infinity" ]
      volumeMounts:
      - name: terraform
        mountPath: /terraform
  volumes:
    - name: terraform
      persistentVolumeClaim:
        claimName: terraform
  restartPolicy: Never
  terminationGracePeriodSeconds: 1
