apiVersion: v1
kind: PersistentVolume
metadata:
  name: terraform
spec:
  storageClassName: terraform
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
      path: "/mnt/terraform"
