apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: terraform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: terraform
subjects:
- kind: ServiceAccount
  name: terraform
