apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: terraform
rules:
# - apiGroups:
#   - ""
#   resources:
#   - secrets
#   verbs:
#   - create
#   - get
#   - patch
#   - delete
#   - list
#   - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - get
  - delete
  - patch
# - apiGroups:
#   - "coordination.k8s.io"
#   resources:
#   - leases
#   verbs:
#   - create
#   - get
#   - update
