apiVersion: v1
kind: Pod
metadata:
  name: terraform
spec:
  serviceAccount: terraform
  initContainers:
    - name: init
      image: "hashicorp/terraform"
      command: [ "terraform", "-chdir=/terraform", "init" ]
      volumeMounts:
      - name: terraform
        mountPath: /terraform
  containers:
    - name: apply
      image: "hashicorp/terraform"
      command: [ "terraform", "-chdir=/terraform", "apply", "-auto-approve" ]
      volumeMounts:
      - name: terraform
        mountPath: /terraform
  volumes:
    - name: terraform
      persistentVolumeClaim:
        claimName: this
  restartPolicy: Never
